ai.api.key=${GROQ_API_KEY}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_JDBC_PARAMETERS:}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false
logging.level.root=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

server.error.include-message=never
server.error.include-stacktrace=never
