spring.application.name=jobinterviewcoach
spring.application.name=jobinterviewcoach

ai.api.key=${GROQ_API_KEY:}
ai.base.url=https://api.groq.com/openai/v1
ai.model=openai/gpt-oss-20b

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:interview_coach}
spring.datasource.username=${DB_USER:interview_coach}
spring.datasource.password=${DB_PASSWORD:interview_coach}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.jpa.open-in-view=false
