CREATE TABLE interview_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    cv_text TEXT NOT NULL,
    job_text TEXT NOT NULL
);

CREATE TABLE interview_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    question_text TEXT NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT fk_interview_question_session
        FOREIGN KEY (session_id) REFERENCES interview_session (id),
    CONSTRAINT uk_interview_question_session_position
        UNIQUE (session_id, position)
);

CREATE TABLE answer_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    user_answer TEXT NOT NULL,
    score VARCHAR(255),
    strengths TEXT,
    missing_points TEXT,
    improvement_tips TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_answer_attempt_question
        FOREIGN KEY (question_id) REFERENCES interview_question (id)
);

-- The unique constraint above indexes session_id first and also enforces question order uniqueness.
CREATE INDEX idx_answer_attempt_question_id ON answer_attempt (question_id);
